server:
  port: 8081

spring:
  application:
    name: ALTEN_ECOMMERCE

  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

  main:
    allow-circular-references: true
  sql:
    init:
      mode: always


logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days



