server:
  port: 8081

spring:
  application:
    name: ALTEN_ECOMMERCE

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  main:
    allow-circular-references: true
  sql:
    init:
      mode: always

  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # a day
     # refresh-token:
       # expiration: 604800000 # 7 days
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
  api-docs:
    enabled: true
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate: ERROR
    com:
      alten:
        ecommerce: DEBUG


