server:
  port: 8081

spring:
  application:
    name: ALTEN_ECOMMERCE

  datasource:
    url: jdbc:mysql://localhost:3306/test_alten?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop   # crée automatiquement les tables à chaque démarrage
    show-sql: true        # affiche les requêtes SQL dans la console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # dialecte MySQL 8

  main:
    allow-circular-references: true

  sql:
    init:
      mode: always

  mvc:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # a day

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
  api-docs:
    enabled: true
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate:
        SQL: DEBUG
    com:
      alten:
        ecommerce: DEBUG
